version: "3.7"

services:
  
  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "4000:1080"
      - "4025:1025"
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "~/rabbitmq/data/:/var/lib/rabbitmq/data"

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "~/redis/data/:/var/lib/redis/data"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes