apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-state
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: host.docker.internal:6379
    - name: redisPassword
      secretKeyRef:
        name: state.redisPassword
        key: state.redisPassword
    - name: actorStateStore
      value: "true"
  auth:
    secretStore: secrets
scopes:
  - muw  
