apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zeebe-validate
  namespace: demo
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
    - name: gatewayAddr
      value: host.docker.internal:26500
    - name: gatewayKeepAlive
      value: 45s
    - name: usePlainTextConnection
      value: true
    - name: jobType
      value: validate
    - name: workerName
      value: muw-worker
scopes:
  - muw